### ISSUE TITLE
Make devices screen

### ISSUE THREAD

**Issue by Mfungorn** [kostya05983/web-bomber#10]
Screen with list of available devices
![Devices](https://user-images.githubusercontent.com/41123969/57065710-84f54f80-6cf4-11e9-8077-40ffefb8c8ef.png)

**Comment by kubitre** [comment]
What would 100 connected devices look like? Somehow minimized images or another component

**Comment by kostya05983** [comment]
instead of right picture we will have a map of devices, with coordinates and so one
